### ISSUE TITLE
Problems with setting it up

### ISSUE THREAD

**Issue by Falkgaard** [pthom/hello_imgui_my_app#1]
Hi!

Sorry if this is a dumb question, but, during step 3:

`cmake .. -DCMAKE_TOOLCHAIN_FILE=../external/hello_imgui/vcpkg/scripts/buildsystems/vcpkg.cmake -DHELLOIMGUI_USE_SDL_OPENGL3=ON`

`CMake Error: The source directory "/home/user/code/MyProject" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.`

How should I proceed in this situation? I'm running Linux (Manjaro) and in general I use Makefiles.

Edit 1: Do I have to switch over to CMake instead of Make? I'm new to CMake, but I'm looking into it now.

Edit 2: Nevermind, I'm an idiot and just read the read me and forgot to actually look at the structure and files in the repo.

**Comment by pthom** [comment]
I think you had forgotten to `cd build_sdl` .
I updated the step 3 to make it more readable.

Is it ok for you, can I close this issue?


Good luck!

**Comment by Falkgaard** [comment]
I see, thank you!
Yep, you can close it!
